# Generated by Django 3.1.1 on 2020-10-01 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201001_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='watcher',
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='watcher',
            field=models.ManyToManyField(null=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
