# Generated by Django 3.1.1 on 2020-10-01 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201001_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wins', to=settings.AUTH_USER_MODEL),
        ),
    ]
