# Generated by Django 3.1.1 on 2020-10-02 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlistings_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='auctions.categories'),
        ),
    ]
